### PR TITLE
Fix determine checkmate bug and add stalemate method and tests

### PR DESCRIPTION
**Pull request by takehiromouri**
# Stalemate

* Checking stalemate is basically the same as checking for checkmate, except the method doesn't check if the King is already in check.
* I noticed the transactions were not rolling back and was causing a bug
  * This was fixed by reloading the piece after the transaction was rolled back
* Included flash message if game is in stalemate

### CODE REVIEW

**Comment by jonathanpike** [comment]
Thanks so much, @takehiromouri, for coming up with this better solution.  When I tried it on my branch with the further tests for checkmate, I actually found *another* bug -- this time in castling!  It was checking for **all** rooks, not just your own rooks.  I've updated the checkmate method and pushed my changes to that branch (since it has the tests, and I refactored the structure of the method).  

If that looks good, you can merge the PR, merge master into this branch, and we can merge stalemate in.

**Comment by jonathanpike** [comment]
I like the `around_action` idea, @takehiromouri.  I think we'll need to do something similar for checkmate, because that means the game is over too.  In that case, though, `winning_player_id` should be set to the correct player.

For stalemate, we need to set the game as over.  This could mean a few things: 

1. Removing the pieces from the board. 
2. Set turn number to nil. 
3. All of the above. 

We also need to set the `winning_player_id` to -1, as was brought up in the user scorecard PR.

**Comment by takehiromouri** [comment]
Refactored some of @jonathanpike 's code so that the game `check_status` before_action.
* It checks for stalemate and checkmate
* If it is one of those, it updates the `winning_game_player_id`

Should be ready to ship!

**Comment by jonathanpike** [comment]
Looks great!  :shipit:

**Pull request merged**
